### ISSUE TITLE
Error Duration To Long

### ISSUE THREAD

**Issue by antony666** [Still34/PsvDecryptCore#2]
I had trouble in the original from kevin wang and it was path to long issue in rare cases it was 2 courses. other then that worked perfect.

Now with this new version it got me the 2 courses i needed that the original couldn't . but it also left an error at the end witch also stopped it from getting another course different from the original 2 courses.

So once i got the 2 courses i needed i got rid of them and left the 3rd course for this program to work its magic that it didn't get in the first run. And it worked fine so i don't know why i got this error.

but here it is :

![error new](https://user-images.githubusercontent.com/7550935/35480738-03798dd0-0469-11e8-91cf-c8966199b3fa.png)

**Comment by Still34** [comment]
Seems to be something to do with the async enumerable parallel lib that this project uses. I'll take a look shortly.

**Comment by antony666** [comment]
Thanks for fast reply very good work

**Comment by antony666** [comment]
This was with 32bit & 64bit

**Comment by Still34** [comment]
Actually, this seems to because of the subtitle's timestamp being outside of `TimeSpan`'s max limit. Could you provide the course name so I could resolve this?

**Comment by antony666** [comment]
Creating Gameplay Systems using Blueprint Features in Unreal Engine

Using Data Tables to Create Data Driven Gameplay in Unreal Engine

I’m 99.9% sure its these 2.... I also dealt with path too long from these 2 as well on the original version !!




This one was in the equation to 

Unreal Particle System Fundamentals

Sent from Mail for Windows 10

**Comment by Still34** [comment]
The issue was caused by a malformed subtitle time stamp, where the `StartTime` was set to a negative value, as seen here. ![](https://i.imgur.com/MwjykNz.png) EF will attempt to resolve the value as something that's far over `TimeSpan.MaxValue` when reading it as a `ulong`.

499a5e8 should resolve this issue by setting the unusual value to 0.

**Comment by antony666** [comment]
wow nice catch so if i re-download this .... will everything be up to date and all fixed
