### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Ant-Anon** [Still34/PsvDecryptCore#3]
i have downloaded the latest to test it out since the last error i had and this is whats happening.

this is the 64bit version

![64bit latest error](https://user-images.githubusercontent.com/7550935/35669500-68bcccd4-0789-11e8-8e3d-2271f434265e.png)

**Comment by Still34** [comment]
Try renaming your PsvDecrpytCore folder. The path is likely too long.

**Comment by Ant-Anon** [comment]
After renaming it ....

![latest error 64bit rename](https://user-images.githubusercontent.com/7550935/35669826-7c44f24e-078a-11e8-923c-f3371c15fe45.png)

**Comment by Ant-Anon** [comment]
Is there something I'm doing wrong

**Comment by Ant-Anon** [comment]
should i be running it as admin
i have changed the name to shorter. 
and i have also used the Path Too Long bypass in the registry

**Comment by Still34** [comment]
It's a Windows limitation. Windows does not allow directories to be named with `.` at the end of it. I'll push a fix for it shortly.

**Comment by Still34** [comment]
0bfa016 fixes this issue by using the returned `DirectoryInfo` instead.

**Comment by Ant-Anon** [comment]
so just re-download the updated version ????

**Comment by Ant-Anon** [comment]
and it should be fixed ???

**Comment by Still34** [comment]
Yes, that is always the case when I push out a new commit that fixes an issue or updates the application. Please note that AppVeyor may take a while to build to the latest application sometimes.

**Comment by Ant-Anon** [comment]
Ok so when you make a change you run it through AppVayer to update the build thats hosted on github

is that correct ????

**Comment by Still34** [comment]
AppVeyor will be notified whenever there is a new commit on the Git, and it will attempt to compile the latest code and push out the artifacts/builds. This is called [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration).

**Comment by Still34** [comment]
Word of advice as well, it would be nice to name your issues according to the actual issue instead of `new error`. Anything like `Path error/exception thrown when trying to...` would be good enough. It'll help the developer keep track of the issue at one glance.

**Comment by Ant-Anon** [comment]
Interesting learn something new everyday....

ok because i'm not that savvy with coding just yet. 

Just so i know i understand this correctly if i name it something like what the error is saying its self that will be good enough . ???

**Comment by Still34** [comment]
Sure. Anything informative about the error will help. Obviously you don't want to copy paste the entire thing in the title, but a shortened version like `When doing this, that throws`.

**Comment by Ant-Anon** [comment]
No worries Thanks for the advice and fast response much appreciated. Cheers Mate

**Comment by Ant-Anon** [comment]
Just tried it now ..... Worked like a charm and also just for sake of it i still renamed the folder shorter but everything worked perfect...
